using System.Text;
using System.Text.Json;
using Dapper;
using Microsoft.EntityFrameworkCore;
using NtbEvent.Application.Contracts.Persistence;
using NtbEvent.Application.Events;
using NtbEvent.Domain.Entities;
using NtbEvent.Domain.Enums;

namespace NtbEvent.Infrastructure.Persistence;

/// <summary>
/// CRUD operations (Add, GetById, GetBySlug, Update, Delete) are handled by Entity Framework Core.
/// The list/filter query (GetAsync) is handled by Dapper for performance with dynamic SQL.
/// </summary>
public sealed class EventRepository : IEventRepository
{
    // ─── Dapper report query ────────────────────────────────────────────────

    private const string SelectColumns = """
        SELECT
            id AS Id,
            created_by_id AS CreatedById,
            slug AS Slug,
            title AS Title,
            summary AS Summary,
            long_description AS LongDescription,
            category AS Category,
            type AS Type,
            status AS Status,
            date_ad AS DateAd,
            end_date_ad AS EndDateAd,
            date_bs AS DateBs,
            end_date_bs AS EndDateBs,
            color AS Color,
            location AS Location,
            region AS Region,
            address AS Address,
            date_range_label AS DateRangeLabel,
            duration_label AS DurationLabel,
            attendance_label AS AttendanceLabel,
            attendance_note AS AttendanceNote,
            entry_type AS EntryType,
            price AS Price,
            rating AS Rating,
            reviews_label AS ReviewsLabel,
            image AS Image,
            map_image AS MapImage,
            organizer AS Organizer,
            organizer_subtitle AS OrganizerSubtitle,
            organizer_verified AS OrganizerVerified,
            organizer_image_url AS OrganizerImageUrl,
            highlights_json::text AS HighlightsJson,
            featured AS Featured,
            read_time AS ReadTime,
            requires_registration AS RequiresRegistration,
            requires_invitation AS RequiresInvitation,
            show_entry_type AS ShowEntryType,
            created_at_utc AS CreatedAtUtc,
            updated_at_utc AS UpdatedAtUtc
        FROM events
        """;

    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web);

    private readonly NtbEventDbContext _dbContext;
    private readonly IDataRepo _dataRepo;

    public EventRepository(NtbEventDbContext dbContext, IDataRepo dataRepo)
    {
        _dbContext = dbContext;
        _dataRepo = dataRepo;
    }

    // ─── EF Core — CRUD ─────────────────────────────────────────────────────

    public async Task<Event> AddAsync(Event entity, CancellationToken cancellationToken = default)
    {
        await _dbContext.Events.AddAsync(entity, cancellationToken);
        await _dbContext.SaveChangesAsync(cancellationToken);
        return entity; // entity.Id is populated by EF after insert (GENERATED BY DEFAULT AS IDENTITY)
    }

    public async Task<Event?> GetByIdAsync(long id, CancellationToken cancellationToken = default)
    {
        // AsNoTracking prevents stale-entity conflicts when UpdateAsync follows immediately
        return await _dbContext.Events
            .AsNoTracking()
            .FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
    }

    public async Task<Event?> GetBySlugAsync(string slug, CancellationToken cancellationToken = default)
    {
        var normalized = slug.Trim().ToLowerInvariant();
        return await _dbContext.Events
            .AsNoTracking()
            .FirstOrDefaultAsync(e => e.Slug == normalized, cancellationToken);
    }

    public async Task<bool> UpdateAsync(Event entity, CancellationToken cancellationToken = default)
    {
        // entity is detached (read with AsNoTracking above); Update() attaches and marks Modified
        _dbContext.Events.Update(entity);
        var affected = await _dbContext.SaveChangesAsync(cancellationToken);
        return affected > 0;
    }

    public async Task<bool> DeleteAsync(long id, CancellationToken cancellationToken = default)
    {
        var entity = await _dbContext.Events.FindAsync([id], cancellationToken);
        if (entity is null)
        {
            return false;
        }

        _dbContext.Events.Remove(entity);
        var affected = await _dbContext.SaveChangesAsync(cancellationToken);
        return affected > 0;
    }

    // ─── Dapper — Report / filter list query ────────────────────────────────

    public async Task<IReadOnlyList<Event>> GetAsync(
        EventFilter filter,
        CancellationToken cancellationToken = default)
    {
        var parameters = new DynamicParameters();
        var where = BuildWhereClause(filter, parameters);
        var orderBy = BuildOrderByClause(filter.SortBy, filter.SortDir);

        var sql = $"{SelectColumns}\n{where}\n{orderBy}";

        var rows = await _dataRepo.QueryAsync<EventRow>(sql, parameters, cancellationToken: cancellationToken);
        return rows.Select(MapRow).ToList();
    }

    public async Task<(IReadOnlyList<Event> Items, int TotalCount)> GetPagedAsync(
        EventFilter filter,
        CancellationToken cancellationToken = default)
    {
        var parameters = new DynamicParameters();
        var where = BuildWhereClause(filter, parameters);
        var orderBy = BuildOrderByClause(filter.SortBy, filter.SortDir);

        var page = Math.Max(1, filter.Page);
        var pageSize = Math.Clamp(filter.PageSize, 1, 100);
        var offset = (page - 1) * pageSize;

        // Count total matching rows (separate query for accuracy)
        var countSql = $"SELECT COUNT(*) FROM events\n{where}";
        var totalCount = await _dataRepo.ExecuteScalarAsync<int>(countSql, parameters, cancellationToken: cancellationToken);

        // Paginated data
        var dataSql = $"{SelectColumns}\n{where}\n{orderBy}\nLIMIT {pageSize} OFFSET {offset}";
        var rows = await _dataRepo.QueryAsync<EventRow>(dataSql, parameters, cancellationToken: cancellationToken);

        return (rows.Select(MapRow).ToList(), totalCount);
    }

    // ─── Private helpers ─────────────────────────────────────────────────────

    private static string BuildWhereClause(EventFilter filter, DynamicParameters parameters)
    {
        var sb = new StringBuilder("WHERE 1 = 1");

        if (!string.IsNullOrWhiteSpace(filter.Status))
        {
            sb.AppendLine("\nAND status = @Status");
            parameters.Add("@Status", filter.Status.Trim().ToLowerInvariant());
        }
        else if (!filter.IncludeDrafts)
        {
            sb.AppendLine("\nAND status = @Status");
            parameters.Add("@Status", "published");
        }

        if (!string.IsNullOrWhiteSpace(filter.Category))
        {
            sb.AppendLine("\nAND category = @Category");
            parameters.Add("@Category", filter.Category.Trim());
        }

        if (!string.IsNullOrWhiteSpace(filter.Region))
        {
            sb.AppendLine("\nAND region = @Region");
            parameters.Add("@Region", filter.Region.Trim());
        }

        if (!string.IsNullOrWhiteSpace(filter.Search))
        {
            sb.AppendLine("\nAND (title ILIKE @Search OR summary ILIKE @Search OR location ILIKE @Search OR region ILIKE @Search)");
            parameters.Add("@Search", $"%{filter.Search.Trim()}%");
        }

        if (filter.FromDate is not null)
        {
            sb.AppendLine("\nAND date_ad >= @FromDate");
            parameters.Add("@FromDate", filter.FromDate.Value.Date);
        }

        if (filter.ToDate is not null)
        {
            sb.AppendLine("\nAND date_ad <= @ToDate");
            parameters.Add("@ToDate", filter.ToDate.Value.Date);
        }

        return sb.ToString();
    }

    private static string BuildOrderByClause(string? sortBy, string? sortDir)
    {
        var direction = string.Equals(sortDir?.Trim(), "desc", StringComparison.OrdinalIgnoreCase) ? "DESC" : "ASC";

        var column = sortBy?.Trim().ToLowerInvariant() switch
        {
            "title"  => "title",
            "rating" => "rating",
            _        => "date_ad"
        };

        // Secondary sort always falls back to date_ad + title for stable paging
        return column == "date_ad"
            ? $"ORDER BY date_ad {direction}, title ASC"
            : $"ORDER BY {column} {direction}, date_ad ASC, title ASC";
    }

    private static Event MapRow(EventRow row)
    {
        return new Event
        {
            Id = row.Id,
            CreatedById = row.CreatedById,
            Slug = row.Slug,
            Title = row.Title,
            Summary = row.Summary,
            LongDescription = row.LongDescription,
            Category = row.Category,
            Type = Enum.TryParse<EventType>(row.Type, ignoreCase: true, out var eventType)
                ? eventType
                : EventType.Event,
            Status = Enum.TryParse<EventLifecycleStatus>(row.Status, ignoreCase: true, out var status)
                ? status
                : EventLifecycleStatus.Draft,
            DateAd = row.DateAd,
            EndDateAd = row.EndDateAd,
            DateBs = row.DateBs,
            EndDateBs = row.EndDateBs,
            Color = row.Color,
            Location = row.Location,
            Region = row.Region,
            Address = row.Address,
            DateRangeLabel = row.DateRangeLabel,
            DurationLabel = row.DurationLabel,
            AttendanceLabel = row.AttendanceLabel,
            AttendanceNote = row.AttendanceNote,
            EntryType = row.EntryType,
            Price = row.Price,
            Rating = row.Rating,
            ReviewsLabel = row.ReviewsLabel,
            Image = ParseImageList(row.Image),
            MapImage = row.MapImage,
            Organizer = row.Organizer,
            OrganizerSubtitle = row.OrganizerSubtitle,
            OrganizerVerified = row.OrganizerVerified,
            OrganizerImageUrl = row.OrganizerImageUrl,
            Highlights = JsonSerializer.Deserialize<List<EventHighlight>>(row.HighlightsJson, JsonOptions) ?? [],
            Featured = row.Featured,
            ReadTime = row.ReadTime,
            RequiresRegistration = row.RequiresRegistration,
            RequiresInvitation = row.RequiresInvitation,
            ShowEntryType = row.ShowEntryType,
            CreatedAtUtc = row.CreatedAtUtc,
            UpdatedAtUtc = row.UpdatedAtUtc
        };
    }

    private static List<string> ParseImageList(string rawImageValue)
    {
        if (string.IsNullOrWhiteSpace(rawImageValue))
        {
            return [];
        }

        var value = rawImageValue.Trim();

        if (value.StartsWith("[", StringComparison.Ordinal))
        {
            try
            {
                var parsed = JsonSerializer.Deserialize<List<string>>(value, JsonOptions) ?? [];
                return parsed
                    .Where(image => !string.IsNullOrWhiteSpace(image))
                    .Select(image => image.Trim())
                    .ToList();
            }
            catch (JsonException)
            {
                return [value];
            }
        }

        return [value];
    }

    // Dapper projection for the report query — maps raw SQL column aliases
    private sealed class EventRow
    {
        public long Id { get; init; }
        public long? CreatedById { get; init; }
        public string Slug { get; init; } = string.Empty;
        public string Title { get; init; } = string.Empty;
        public string Summary { get; init; } = string.Empty;
        public string LongDescription { get; init; } = string.Empty;
        public string Category { get; init; } = string.Empty;
        public string Type { get; init; } = string.Empty;
        public string Status { get; init; } = string.Empty;
        public DateTime DateAd { get; init; }
        public DateTime EndDateAd { get; init; }
        public string DateBs { get; init; } = string.Empty;
        public string EndDateBs { get; init; } = string.Empty;
        public string Color { get; init; } = string.Empty;
        public string Location { get; init; } = string.Empty;
        public string Region { get; init; } = string.Empty;
        public string Address { get; init; } = string.Empty;
        public string DateRangeLabel { get; init; } = string.Empty;
        public string DurationLabel { get; init; } = string.Empty;
        public string AttendanceLabel { get; init; } = string.Empty;
        public string AttendanceNote { get; init; } = string.Empty;
        public string EntryType { get; init; } = string.Empty;
        public decimal Price { get; init; }
        public decimal Rating { get; init; }
        public string ReviewsLabel { get; init; } = string.Empty;
        public string Image { get; init; } = string.Empty;
        public string MapImage { get; init; } = string.Empty;
        public string Organizer { get; init; } = string.Empty;
        public string OrganizerSubtitle { get; init; } = string.Empty;
        public bool OrganizerVerified { get; init; }
        public string? OrganizerImageUrl { get; init; }
        public string HighlightsJson { get; init; } = "[]";
        public bool Featured { get; init; }
        public string ReadTime { get; init; } = string.Empty;
        public bool RequiresRegistration { get; init; }
        public bool RequiresInvitation { get; init; }
        public bool ShowEntryType { get; init; }
        public DateTime CreatedAtUtc { get; init; }
        public DateTime UpdatedAtUtc { get; init; }
    }
}
