using Moq;
using NtbEvent.Application.Contracts.Persistence;
using NtbEvent.Application.Contracts.Services;
using NtbEvent.Application.Events.Dtos;
using NtbEvent.Application.Services;
using NtbEvent.Domain.Entities;
using NtbEvent.Domain.Enums;

namespace NtbEvent.Tests.Unit.Events;

/// <summary>Mid-term report §4.2.1 UT-04..UT-06 (Event CRUD).</summary>
public sealed class EventServiceTests
{
    private readonly Mock<IEventRepository> _eventRepository = new();
    private readonly EventService _sut;

    public EventServiceTests()
    {
        _sut = new EventService(_eventRepository.Object, new PopularityScoreService());
    }

    private static SaveEventRequest ValidRequest() => new()
    {
        Title = "Kathmandu Street Food Festival",
        Summary = "A celebration of Nepali street food.",
        LongDescription = "Full description of the food festival.",
        Category = "Food",
        Type = "event",
        DateAd = new DateTime(2026, 10, 12),
        Location = "Basantapur",
        Region = "Kathmandu",
        Organizer = "NTB"
    };

    // UT-04: Create event with all fields -> event persisted, slug auto-generated.
    [Fact]
    public async Task CreateEventAsync_AllFields_PersistsWithAutoGeneratedSlug()
    {
        _eventRepository.Setup(r => r.GetBySlugAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((Event?)null);
        _eventRepository.Setup(r => r.AddAsync(It.IsAny<Event>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((Event e, CancellationToken _) =>
            {
                e.Id = 42;
                return e;
            });

        var result = await _sut.CreateEventAsync(ValidRequest(), createdByUserId: 1);

        Assert.Equal(42, result.Id);
        Assert.Equal("kathmandu-street-food-festival", result.Slug);
        _eventRepository.Verify(r => r.AddAsync(
            It.Is<Event>(e => e.Slug == "kathmandu-street-food-festival" && e.Title == "Kathmandu Street Food Festival"),
            It.IsAny<CancellationToken>()), Times.Once);
    }

    // UT-05: Update event status to Published -> status updated (persisted via repository).
    [Fact]
    public async Task UpdateEventAsync_StatusChangedToPublished_PersistsUpdatedStatus()
    {
        var existing = new Event
        {
            Id = 5,
            Slug = "existing-event",
            Title = "Existing Event",
            Status = EventLifecycleStatus.Draft,
            DateAd = new DateTime(2026, 5, 1),
            EndDateAd = new DateTime(2026, 5, 1)
        };
        _eventRepository.Setup(r => r.GetByIdAsync(5, It.IsAny<CancellationToken>())).ReturnsAsync(existing);
        _eventRepository.Setup(r => r.GetBySlugAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((Event?)null);
        _eventRepository.Setup(r => r.UpdateAsync(It.IsAny<Event>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(true);

        var request = ValidRequest();
        request.Slug = existing.Slug;
        request.Status = "published";

        var result = await _sut.UpdateEventAsync(5, request, updatedByUserId: 2);

        Assert.NotNull(result);
        Assert.Equal("published", result!.Status);
        _eventRepository.Verify(r => r.UpdateAsync(
            It.Is<Event>(e => e.Status == EventLifecycleStatus.Published),
            It.IsAny<CancellationToken>()), Times.Once);
    }

    // UT-06: Delete event by ID -> event removed.
    [Fact]
    public async Task DeleteEventAsync_ExistingId_RemovesEvent()
    {
        _eventRepository.Setup(r => r.DeleteAsync(7, It.IsAny<CancellationToken>())).ReturnsAsync(true);

        var deleted = await _sut.DeleteEventAsync(7);

        Assert.True(deleted);
        _eventRepository.Verify(r => r.DeleteAsync(7, It.IsAny<CancellationToken>()), Times.Once);
    }
}
