using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NtbEvent.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class CreateEventsBaseTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // The "events" table predates the migration history (it was created via
            // EnsureCreated/manual setup on existing environments), so later migrations
            // only ever ALTER/ADD COLUMN against it. A brand-new database has no such
            // table, so create it here first, idempotently, with the columns that were
            // present at the start of the migration history (later migrations add the rest).
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS events (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    address TEXT NOT NULL,
                    attendance_label TEXT NOT NULL,
                    attendance_note TEXT NOT NULL,
                    category TEXT NOT NULL,
                    color TEXT NOT NULL,
                    created_at_utc TIMESTAMPTZ NOT NULL,
                    date_ad DATE NOT NULL,
                    date_bs TEXT NOT NULL,
                    date_range_label TEXT NOT NULL,
                    duration_label TEXT NOT NULL,
                    end_date_ad DATE NOT NULL,
                    entry_type TEXT NOT NULL,
                    featured BOOLEAN NOT NULL,
                    highlights_json JSONB NOT NULL,
                    image TEXT NOT NULL,
                    location TEXT NOT NULL,
                    long_description TEXT NOT NULL,
                    map_image TEXT NOT NULL,
                    organizer TEXT NOT NULL,
                    organizer_subtitle TEXT NOT NULL,
                    organizer_verified BOOLEAN NOT NULL,
                    price NUMERIC(12,2) NOT NULL,
                    rating NUMERIC(4,2) NOT NULL,
                    read_time TEXT NOT NULL,
                    region TEXT NOT NULL,
                    reviews_label TEXT NOT NULL,
                    slug TEXT NOT NULL,
                    status TEXT NOT NULL,
                    summary TEXT NOT NULL,
                    tags_json JSONB NOT NULL DEFAULT '[]',
                    title TEXT NOT NULL,
                    type TEXT NOT NULL,
                    updated_at_utc TIMESTAMPTZ NOT NULL
                );
            ");

            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_events_slug"" ON events(slug);
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS idx_events_status_date ON events(status, date_ad);
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "events");
        }
    }
}
