using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NtbEvent.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class CreateUsersRefreshTokensAndEventSchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Users and refresh_tokens tables may already exist from raw SQL initialization
            // Use raw SQL to handle this gracefully
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    full_name VARCHAR(160) NOT NULL,
                    email VARCHAR(200) NOT NULL,
                    normalized_email VARCHAR(200) NOT NULL,
                    password_hash VARCHAR(500) NOT NULL,
                    department VARCHAR(120) NOT NULL,
                    role TEXT NOT NULL,
                    is_active BOOLEAN NOT NULL,
                    last_login_at_utc TIMESTAMPTZ NULL,
                    created_by_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
                    created_at_utc TIMESTAMPTZ NOT NULL,
                    updated_at_utc TIMESTAMPTZ NOT NULL
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS refresh_tokens (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    token_hash VARCHAR(64) NOT NULL,
                    token_family VARCHAR(64) NOT NULL,
                    expires_at_utc TIMESTAMPTZ NOT NULL,
                    created_by_ip VARCHAR(128) NOT NULL,
                    user_agent VARCHAR(400) NOT NULL,
                    revoked_at_utc TIMESTAMPTZ NULL,
                    revoked_by_ip VARCHAR(128) NULL,
                    replaced_by_token_hash VARCHAR(64) NULL,
                    revocation_reason VARCHAR(256) NULL,
                    created_at_utc TIMESTAMPTZ NOT NULL,
                    updated_at_utc TIMESTAMPTZ NOT NULL
                );
            ");

            // Create indexes for users table if they don't exist
            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ux_users_normalized_email ON users(normalized_email);
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_users_created_by_user_id"" ON users(created_by_user_id);
            ");

            // Create indexes for refresh_tokens table if they don't exist
            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ux_refresh_tokens_token_hash ON refresh_tokens(token_hash);
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS idx_refresh_tokens_token_family ON refresh_tokens(token_family);
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens(user_id);
            ");

            // Add columns to events table if they don't exist
            migrationBuilder.Sql(@"
                ALTER TABLE IF EXISTS events
                ADD COLUMN IF NOT EXISTS created_by_id BIGINT;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE IF EXISTS events
                ADD COLUMN IF NOT EXISTS updated_by_id BIGINT;
            ");

            // Create indexes for events table foreign keys if they don't exist
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_events_created_by_id"" ON events(created_by_id);
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_events_updated_by_id"" ON events(updated_by_id);
            ");

            // Add foreign key constraints if they don't exist
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.table_constraints 
                        WHERE constraint_name = 'FK_events_users_created_by_id'
                    ) THEN
                        ALTER TABLE events
                        ADD CONSTRAINT ""FK_events_users_created_by_id""
                        FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE RESTRICT;
                    END IF;
                END
                $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.table_constraints 
                        WHERE constraint_name = 'FK_events_users_updated_by_id'
                    ) THEN
                        ALTER TABLE events
                        ADD CONSTRAINT ""FK_events_users_updated_by_id""
                        FOREIGN KEY (updated_by_id) REFERENCES users(id) ON DELETE RESTRICT;
                    END IF;
                END
                $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_events_users_created_by_id",
                table: "events");

            migrationBuilder.DropForeignKey(
                name: "FK_events_users_updated_by_id",
                table: "events");

            migrationBuilder.DropIndex(
                name: "IX_events_created_by_id",
                table: "events");

            migrationBuilder.DropIndex(
                name: "IX_events_updated_by_id",
                table: "events");

            migrationBuilder.DropColumn(
                name: "created_by_id",
                table: "events");

            migrationBuilder.DropColumn(
                name: "updated_by_id",
                table: "events");

            migrationBuilder.DropTable(
                name: "refresh_tokens");

            migrationBuilder.DropTable(
                name: "users");
        }
    }
}
