using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NtbEvent.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddEventInvitations : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // ─── invitation_guests (one row per unique person, normalized) ──────
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS invitation_guests (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    full_name VARCHAR(160) NOT NULL,
                    email VARCHAR(200) NOT NULL,
                    normalized_email VARCHAR(200) NOT NULL,
                    phone VARCHAR(40) NOT NULL,
                    organization VARCHAR(160) NOT NULL,
                    created_at_utc TIMESTAMPTZ NOT NULL,
                    updated_at_utc TIMESTAMPTZ NOT NULL
                );
            ");

            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ux_invitation_guests_normalized_email
                ON invitation_guests(normalized_email);
            ");

            // ─── event_invitations (event ↔ guest association + token/status) ───
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS event_invitations (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
                    guest_id BIGINT NOT NULL REFERENCES invitation_guests(id) ON DELETE CASCADE,
                    token VARCHAR(80) NOT NULL,
                    status VARCHAR(20) NOT NULL,
                    invited_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
                    sent_at_utc TIMESTAMPTZ NULL,
                    expires_at_utc TIMESTAMPTZ NULL,
                    verified_at_utc TIMESTAMPTZ NULL,
                    verified_by_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
                    created_at_utc TIMESTAMPTZ NOT NULL,
                    updated_at_utc TIMESTAMPTZ NOT NULL
                );
            ");

            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ux_event_invitations_token
                ON event_invitations(token);
            ");

            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ux_event_invitations_event_guest
                ON event_invitations(event_id, guest_id);
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_event_invitations_guest_id""
                ON event_invitations(guest_id);
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_event_invitations_invited_by_user_id""
                ON event_invitations(invited_by_user_id);
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_event_invitations_verified_by_user_id""
                ON event_invitations(verified_by_user_id);
            ");

            // ─── invitation_scans (audit of each scan attempt) ──────────────────
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS invitation_scans (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    invitation_id BIGINT NOT NULL REFERENCES event_invitations(id) ON DELETE CASCADE,
                    scanned_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
                    result VARCHAR(20) NOT NULL,
                    scanned_at_utc TIMESTAMPTZ NOT NULL,
                    created_at_utc TIMESTAMPTZ NOT NULL,
                    updated_at_utc TIMESTAMPTZ NOT NULL
                );
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS idx_invitation_scans_invitation_id
                ON invitation_scans(invitation_id);
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_invitation_scans_scanned_by_user_id""
                ON invitation_scans(scanned_by_user_id);
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS invitation_scans;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS event_invitations;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS invitation_guests;");
        }
    }
}
