// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NtbEvent.Infrastructure.Persistence;

#nullable disable

namespace NtbEvent.Infrastructure.Migrations
{
    [DbContext(typeof(NtbEventDbContext))]
    [Migration("20260528075600_CreateEventsBaseTable")]
    partial class CreateEventsBaseTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NtbEvent.Domain.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("AttendanceLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attendance_label");

                    b.Property<string>("AttendanceNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attendance_note");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("DateAd")
                        .HasColumnType("date")
                        .HasColumnName("date_ad");

                    b.Property<string>("DateBs")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("date_bs");

                    b.Property<string>("DateRangeLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("date_range_label");

                    b.Property<string>("DurationLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("duration_label");

                    b.Property<DateTime>("EndDateAd")
                        .HasColumnType("date")
                        .HasColumnName("end_date_ad");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entry_type");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean")
                        .HasColumnName("featured");

                    b.Property<string>("Highlights")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("highlights_json");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("long_description");

                    b.Property<string>("MapImage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("map_image");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organizer");

                    b.Property<string>("OrganizerSubtitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organizer_subtitle");

                    b.Property<bool>("OrganizerVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("organizer_verified");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("rating");

                    b.Property<string>("ReadTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("read_time");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("ReviewsLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reviews_label");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags_json");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status", "DateAd")
                        .HasDatabaseName("idx_events_status_date");

                    b.ToTable("events", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
